### ISSUE TITLE
Capítulo HTML

### ISSUE THREAD

**Issue by bahartmann** [roberto/ruby-web-dev-intro#4]
...formulário e componentes que serão úteis para o "mural"
- [x] abordar itens de formulário (form, input, button)
- [x] criar lista de posts

**Comment by roberto** [comment]
Vamos utilizar o material da @inajaraleppa https://www.gitbook.com/book/inajaraleppa/html-e-css/details e colocá-la como autora.

**Comment by roberto** [comment]
O form ficou como um bônus, já que temos que imprimir amanhã.

**Comment by roberto** [comment]
tudo feito.
